/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesAndMain;

import musicshopsystem.Book;
import musicshopsystem.Device;
import musicshopsystem.MusicCDs;
import musicshopsystem.ProductSystem;
import musicshopsystem.TechSpec;

/**
 *
 * @author comteibra
 */
public class AddFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageProduct
     */
    public AddFrame(MainFrame mf) {
        initComponents();
        typeField.setVisible(false);
        typeLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectTypeLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        manufacturerField = new javax.swing.JTextField();
        artistLabel = new javax.swing.JLabel();
        artistField = new javax.swing.JTextField();
        mrcLabel = new javax.swing.JLabel();
        mrcField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 320));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("New Product");

        selectTypeLabel.setText("Select type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Music CD", "Book", "Device" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("                 ID:");

        nameLabel.setText("            Name:");

        jLabel3.setText("Manufacturer:");

        artistLabel.setText("Artist:");

        mrcLabel.setText("MRC:");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        typeLabel.setText("Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectTypeLabel)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mrcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mrcField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(artistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addComponent(artistField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manufacturerField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(selectTypeLabel))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(artistLabel))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(mrcLabel))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manufacturerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(typeLabel))))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        int id;
        String name, manufacturer;
        boolean val;
        
        int type = jComboBox1.getSelectedIndex();
        
        switch (type) {
            case 0:
                String artist, mrc;
                
                id = Integer.parseInt(idField.getText());
                name = nameField.getText();
                manufacturer = manufacturerField.getText();
                artist = artistField.getText();
                mrc = mrcField.getText();
                
                MusicCDs mcds = new MusicCDs(artist, mrc, id, name, manufacturer);
                
                val = ProductSystem.addProduct(mcds);
                if (!val) {
                    messageLabel.setText("Product with this id already exists!");
                } else {
                    messageLabel.setText("Product is added!");
                }
                break;
                
            case 1:
                int edition;
                String author;
                
                id = Integer.parseInt(idField.getText());
                name = nameField.getText();
                manufacturer = manufacturerField.getText();
                author = artistField.getText();
                edition = Integer.parseInt(mrcField.getText());
                
                Book book = new Book(author, edition, id, name, manufacturer);
                
                val = ProductSystem.addProduct(book);
                if (!val) {
                    messageLabel.setText("Product with this id already exists!");
                } else {
                    messageLabel.setText("Product is added!");
                }
                break;
                
            case 2:
                String dtype, color, connection;
                
                id = Integer.parseInt(idField.getText());
                name = nameField.getText();
                manufacturer = manufacturerField.getText();
                color = artistField.getText();
                connection = mrcField.getText();
                dtype = typeField.getText();
                
                Device device = new Device(dtype, id, name, manufacturer);
                TechSpec ts = new TechSpec(color, connection);
                device.addTechSpec(ts);
                
                val = ProductSystem.addProduct(device);
                if (!val) {
                    messageLabel.setText("Product with this id already exists!");
                } else {
                    messageLabel.setText("Product is added!");
                }
                break;
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() == 0) {
            artistLabel.setText("Artist:");
            mrcLabel.setText("MRC:");
            typeField.setVisible(false);
            typeLabel.setVisible(false);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            artistLabel.setText("Author:");
            mrcLabel.setText("Edition:");
            typeField.setVisible(false);
            typeLabel.setVisible(false);
        } else if (jComboBox1.getSelectedIndex() == 2) {
            artistLabel.setText("Color:");
            mrcLabel.setText("Connection:");
            typeField.setVisible(true);
            typeLabel.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int id;
        String name, manufacturer;
        boolean val;
        
        int type = jComboBox1.getSelectedIndex();
        
        switch (type) {
            case 0:
                String artist, mrc;
                
                id = Integer.parseInt(idField.getText());
                name = nameField.getText();
                manufacturer = manufacturerField.getText();
                artist = artistField.getText();
                mrc = mrcField.getText();
                
                MusicCDs mcds = new MusicCDs(artist, mrc, id, name, manufacturer);
                
                val = ProductSystem.addProduct(mcds);
                if (!val) {
                    messageLabel.setText("Product with this id already exists!");
                } else {
                    messageLabel.setText("Product is added!");
                }
                break;
                
            case 1:
                int edition;
                String author;
                
                id = Integer.parseInt(idField.getText());
                name = nameField.getText();
                manufacturer = manufacturerField.getText();
                author = artistField.getText();
                edition = Integer.parseInt(mrcField.getText());
                
                Book book = new Book(author, edition, id, name, manufacturer);
                
                val = ProductSystem.addProduct(book);
                if (!val) {
                    messageLabel.setText("Product with this id already exists!");
                } else {
                    messageLabel.setText("Product is added!");
                }
                break;
                
            case 2:
                String dtype, color, connection;
                
                id = Integer.parseInt(idField.getText());
                name = nameField.getText();
                manufacturer = manufacturerField.getText();
                color = artistField.getText();
                connection = mrcField.getText();
                dtype = typeField.getText();
                
                Device device = new Device(dtype, id, name, manufacturer);
                TechSpec ts = new TechSpec(color, connection);
                device.addTechSpec(ts);
                
                val = ProductSystem.addProduct(device);
                if (!val) {
                    messageLabel.setText("Product with this id already exists!");
                } else {
                    messageLabel.setText("Product is added!");
                }
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField artistField;
    private javax.swing.JLabel artistLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField manufacturerField;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField mrcField;
    private javax.swing.JLabel mrcLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel selectTypeLabel;
    private javax.swing.JTextField typeField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
